<?php
   setlocale(LC_ALL,"es_VE.UTF8");
   require_once("../../modulos/pdf/clsFpdf.php");
   require_once("../../clases/reportes/cls_Solicitudes.php");
   session_start();
   $lobjPdf=new clsFpdf();
   $lobjPdf=new clsFpdf();
   $lobjPdf->AliasNbPages();
   $lobjPdf->AddPage("P","Letter");
   $lobjPdf->SetMargins(30,30,30);
   $lobjPdf->SetFont("arial","B",12);
   $lobjConstEst= new cls_Solicitudes();
   $id=$_GET['id'];
   //$buscar=$_SESSION['usuario']['Cedula'];
   //$lobjConstEst->fSetsbusqueda($buscar);
   $laMatriz=$lobjConstEst->fBuscartipo($id);
   //$laMatriz=$lobjConstEst->fBusqueda();
    $Fecha=date("d/m/Y");

    if ($laMatriz[0][1]==1) {
      $lobjPdf->Ln();
     $lobjPdf->SetMargins(40,30,30);
     $lobjPdf->Cell(0,6,utf8_decode("SOLICITUD DE REINGRESO"),0,1,"C");
     $lobjPdf->SetFont("arial","B",10);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6, utf8_decode("DE ESTUDIANTE: ".$laMatriz[0][2]." ".$laMatriz[0][3]." ".$laMatriz[0][0]." MATRICULA: "),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("PARA EL SECRETARIO GENERAL DE LA UNEFA"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("ASUNTO: REINGRESO."),0,"L",false);
     $lobjPdf->SetFont("arial","",10);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6, utf8_decode("  Tengo el agrado de dirigirme a usted, con la finalidad de solicitar formalmente".
                                            " el reingreso a esta casa de estudio donde cursaba: ".$laMatriz[0][5]." en el Término/Semestre: ___________ ".
                                            " Turno: ______________."),0,"J",false);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6,utf8_decode("Dicha solicitud obedece a motivos que a continuación expongo: ".$laMatriz[0][4]."."),0,"J",false);
     $lobjPdf->Cell(0,6,utf8_decode("Atentamente: ".$laMatriz[0][2]." ".$laMatriz[0][3]),0,1,"L");
     $lobjPdf->Cell(0,6,utf8_decode("Correo Electrónico: ".$laMatriz[0][8]),0,1,"L");
     $lobjPdf->Cell(0,6,utf8_decode("Telefono: ".$laMatriz[0][9]),0,1,"L");
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","B",8);
     $lobjPdf->Cell(0,6,utf8_decode("SOLO PARA SER LLENADO POR ESTUDIANTES QUE DESEEN CAMBIO DE CARRERA:"),0,1,"L");
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("CARRERA: ".$laMatriz[0][10]." RÉGIMEN: ".$laMatriz[0][11]),0,"L",false);
     $lobjPdf->SetFont("arial","B",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Solo para uso de la División de Secretaria:"),0,"L",false);
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Nombre, Apellido Y Cédula de Identidad del Funcionario Receptor: ___________________________________________________________________________________________"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Fecha: _____________   Índice Académico: ________________________________________________"),0,"L",false);
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("NOTA: Anexar fotocopias del carne estudiantil o cédula de identidad y constancia de inscripción, Record Académico Original (Constancia de Notas Copia de la Matriz curricular para los CPP-Postgrado) soportes que sustente la solicitud.
Esta planilla debe ir sin enmienda, ser llenada en su totalidad."),1,"L",false);
    }else if ($laMatriz[0][1]==5) {										
       $lobjPdf->Ln();
  	   $lobjPdf->SetMargins(40,30,30);
  	   $lobjPdf->Cell(0,6,utf8_decode("SOLICITUD DE RETIRO POR PROPIA VOLUNTAD (RPV)"),0,1,"C");
  	   $lobjPdf->SetFont("arial","B",10);
       $lobjPdf->Ln();
       $lobjPdf->MultiCell(0, 6, utf8_decode("DE ESTUDIANTE: ".$laMatriz[0][2]." ".$laMatriz[0][3]." ".$laMatriz[0][0]." MATRICULA: ______________"),0,"L",false);
       $lobjPdf->MultiCell(0, 6, utf8_decode("PARA EL SECRETARIO GENERAL DE LA UNEFA"),0,"L",false);
       $lobjPdf->MultiCell(0, 6, utf8_decode("ASUNTO:  SOLICITUD DE RETIRO POR PROPIA VOLUNTAD."),0,"L",false);
       $lobjPdf->SetFont("arial","",10);
       $lobjPdf->Ln();
       $lobjPdf->MultiCell(0, 6, utf8_decode("  Tengo el agrado de dirigirme a usted, con la finalidad de solicitar formalmente el retiro solicitud de retiro por propia voluntad (RPV)."),0,"J",false);
       $lobjPdf->Ln();
       $lobjPdf->MultiCell(0, 6,utf8_decode("Dicha solicitud obedece a motivos que a continuación expongo: ".$laMatriz[0][4]."."),0,"J",false);
       $lobjPdf->Cell(0,6,utf8_decode("Atentamente: ".$laMatriz[0][2]." ".$laMatriz[0][3]),0,1,"L");
       $lobjPdf->Ln();
       $lobjPdf->SetFont("arial","",8);
       $lobjPdf->Cell(40,6,utf8_decode("Carrera o Programa:"),1,0,"L");
       $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][5]),1,0,"L");
       $lobjPdf->Cell(20,6,utf8_decode("Matricula:"),1,0,"L");
       $lobjPdf->Cell(30,6,utf8_decode(""),1,1,"L");
       $lobjPdf->Cell(40,6,utf8_decode("Período Academico:"),1,0,"L");
       $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][6]),1,0,"L");
       $lobjPdf->Cell(20,6,utf8_decode("Semestre"),1,0,"L");
       $lobjPdf->Cell(30,6,utf8_decode(''),1,1,"L");
       $lobjPdf->Cell(40,6,utf8_decode("Núcleo:"),1,0,"L");
       $lobjPdf->Cell(55,6,utf8_decode("Portuguesa"),1,0,"L");
       $lobjPdf->Cell(20,6,utf8_decode("Fecha:"),1,0,"L");
       $lobjPdf->Cell(30,6,utf8_decode($Fecha),1,1,"L");
       $lobjPdf->Cell(40,6,utf8_decode("Correo Electronico:"),1,0,"L");
       $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][8]),1,0,"L");
       $lobjPdf->Cell(20,6,utf8_decode("Telefono:"),1,0,"L");
       $lobjPdf->Cell(30,6,utf8_decode($laMatriz[0][9]),1,1,"L");
       $lobjPdf->Ln();
       $lobjPdf->SetFont("arial","B",8);
       $lobjPdf->MultiCell(0, 6, utf8_decode("Solo para uso de la División de Secretaria:"),0,"L",false);
       $lobjPdf->SetFont("arial","",8);
       $lobjPdf->MultiCell(0, 6, utf8_decode("Nombre, Apellido Y Cédula de Identidad del Funcionario Receptor: ___________________________________________________________________________________________"),0,"L",false);
       $lobjPdf->MultiCell(0, 6, utf8_decode("Fecha: ________________  Índice Académico: ________________________________________________"),0,"L",false);
       $lobjPdf->Ln();
       $lobjPdf->SetFont("arial","",8);
       $lobjPdf->MultiCell(0, 6, utf8_decode("NOTA: Anexar fotocopias del carne estudiantil o cédula de identidad y constancia de inscripción, Record Académico.
  Esta planilla debe ir sin enmienda, ser llenada en su totalidad."),1,"L",false);
       $lobjPdf->SetFont("arial","",10);
    }else if($laMatriz[0][1]==7){
       $lobjPdf->Ln();
     $lobjPdf->SetMargins(40,30,30);
     $lobjPdf->Cell(0,6,utf8_decode("SOLICITUD DE RETIRO POR MOTIVO DE SERVICIOS (RMS)"),0,1,"C");
     $lobjPdf->SetFont("arial","B",10);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6, utf8_decode("DE ESTUDIANTE: ".$laMatriz[0][2]." ".$laMatriz[0][3]." ".$laMatriz[0][0]." MATRICULA: ______________"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("PARA EL SECRETARIO GENERAL DE LA UNEFA"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("ASUNTO:  SOLICITUD DE RETIRO POR MOTIVO DE SALUD."),0,"L",false);
     $lobjPdf->SetFont("arial","",10);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6, utf8_decode("  Tengo el agrado de dirigirme a usted, con la finalidad de solicitar formalmente el retiro solicitud de retiro por motivos de Salud (RMS)."),0,"J",false);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6,utf8_decode("Dicha solicitud obedece a motivos que a continuación expongo: ".$laMatriz[0][4]."."),0,"J",false);
     $lobjPdf->Cell(0,6,utf8_decode("Atentamente: ".$laMatriz[0][2]." ".$laMatriz[0][3]),0,1,"L");
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->Cell(40,6,utf8_decode("Carrera o Programa:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][5]),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Matricula:"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode(""),1,1,"L");
     $lobjPdf->Cell(40,6,utf8_decode("Período Academico:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][6]),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Semestre"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode(''),1,1,"L");
     $lobjPdf->Cell(40,6,utf8_decode("Núcleo:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode("Portuguesa"),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Fecha:"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode($laMatriz[0][7]),1,1,"L");
     $lobjPdf->Cell(40,6,utf8_decode("Correo Electronico:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][8]),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Telefono:"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode($laMatriz[0][9]),1,1,"L");
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","B",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Solo para uso de la División de Secretaria:"),0,"L",false);
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Nombre, Apellido Y Cédula de Identidad del Funcionario Receptor: ___________________________________________________________________________________________"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Fecha: ___________   Índice Académico: ________________________________________________"),0,"L",false);
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("NOTA: Anexar fotocopias del carne estudiantil o cédula de identidad, Record Académico y constancia de inscripción e informe médico original.
Esta planilla debe ir sin enmienda, ser llenada en su totalidad."),1,"L",false);
     $lobjPdf->SetFont("arial","",10);

    }else if($laMatriz[0][1]==6){
      $lobjPdf->Ln();
     $lobjPdf->SetMargins(40,30,30);
     $lobjPdf->Cell(0,6,utf8_decode("SOLICITUD DE RETIRO POR MOTIVO DE SALUD (RPS)"),0,1,"C");
     $lobjPdf->SetFont("arial","B",10);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6, utf8_decode("DE ESTUDIANTE: ".$laMatriz[0][2]." ".$laMatriz[0][3]." ".$laMatriz[0][0]." MATRICULA: ______________"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("PARA EL SECRETARIO GENERAL DE LA UNEFA"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("ASUNTO:  SOLICITUD DE RETIRO POR MOTIVO DE SALUD."),0,"L",false);
     $lobjPdf->SetFont("arial","",10);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6, utf8_decode("  Tengo el agrado de dirigirme a usted, con la finalidad de solicitar formalmente el retiro solicitud de retiro por motivos de Salud (RPS)."),0,"J",false);
     $lobjPdf->Ln();
     $lobjPdf->MultiCell(0, 6,utf8_decode("Dicha solicitud obedece a motivos que a continuación expongo: ".$laMatriz[0][4]."."),0,"J",false);
     $lobjPdf->Cell(0,6,utf8_decode("Atentamente: ".$laMatriz[0][2]." ".$laMatriz[0][3]),0,1,"L");
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->Cell(40,6,utf8_decode("Carrera o Programa:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][5]),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Matricula:"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode(""),1,1,"L");
     $lobjPdf->Cell(40,6,utf8_decode("Período Academico:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][6]),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Semestre"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode(''),1,1,"L");
     $lobjPdf->Cell(40,6,utf8_decode("Núcleo:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode("Portuguesa"),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Fecha:"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode($laMatriz[0][7]),1,1,"L");
     $lobjPdf->Cell(40,6,utf8_decode("Correo Electronico:"),1,0,"L");
     $lobjPdf->Cell(55,6,utf8_decode($laMatriz[0][8]),1,0,"L");
     $lobjPdf->Cell(20,6,utf8_decode("Telefono:"),1,0,"L");
     $lobjPdf->Cell(30,6,utf8_decode($laMatriz[0][9]),1,1,"L");
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","B",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Solo para uso de la División de Secretaria:"),0,"L",false);
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Nombre, Apellido Y Cédula de Identidad del Funcionario Receptor: ___________________________________________________________________________________________"),0,"L",false);
     $lobjPdf->MultiCell(0, 6, utf8_decode("Fecha: ____________   Índice Académico: ________________________________________________"),0,"L",false);
     $lobjPdf->Ln();
     $lobjPdf->SetFont("arial","",8);
     $lobjPdf->MultiCell(0, 6, utf8_decode("NOTA: Anexar fotocopias del carne estudiantil o cédula de identidad, Record Académico y constancia de inscripción e informe médico original.
Esta planilla debe ir sin enmienda, ser llenada en su totalidad."),1,"L",false);
     $lobjPdf->SetFont("arial","",10);
    }
    $lobjPdf->Output('Planilla Solicitud UNEFA','I');
    // echo "<pre>";
     //print_r($laMatriz);
?>
